### 颜色空间

In [1]:
import cv2

cat = cv2.imread('./cat.jpg')
cv2.imshow('cat',cat)

cv2.waitKey(0)
cv2.destoryAllWindows()

AttributeError: module 'cv2' has no attribute 'destoryAllWindows'

In [ ]:
from pandas import DataFrame

In [4]:
# 用每一个像素创建 dataframe
df = DataFrame(cat.reshape(-1,3))

In [5]:
df.head

<bound method NDFrame.head of           0    1    2
0        40  154  254
1        40  154  254
2        42  155  252
3        43  156  252
4        49  159  254
...      ..  ...  ...
1161520  65  131  210
1161521  43  109  188
1161522  63  128  203
1161523  45  107  178
1161524  32   92  162

[1161525 rows x 3 columns]>

In [12]:
c_sum = df.shape - df.duplicated().sum() # 总共颜色 - 判断是否重复的颜色（即重复过的颜色） = 图片颜色种类
c_sum

array([  158750, -1002772])

In [1]:
"""
代码总结：
当可滚动控件 trackbar 滑倒以下数值时：
0：图片以 RGBA 的形式展示（A为透明度）
1：图片以 BGRA 的形式展示
2：图片以 GRAY 的形式展示
3：图片以 HSV 的形式展示
4：图片以 YUV 的形式展示
"""
# 关键API cv2.cvtColor
import cv2

def callback(value):
    pass

cv2.namedWindow('color',cv2.WINDOW_NORMAL)
cv2.resizeWindow('color',640,480)

# 读取照片,OpenCV 读进来的图片默认是 BGR 的色彩空间
img = cv2.imread('./cat.jpg')

# 定义颜色空间转化列表
color_spaces = [
    # 所有颜色空间的的转化都是 COLOR 开头
    cv2.COLOR_BGR2RGBA, cv2.COLOR_BGR2BGRA,
    cv2.COLOR_BGR2GRAY, cv2.COLOR_BGR2HSV,
    cv2.COLOR_BGR2YUV
]

# 设置trackbar
cv2.createTrackbar('trackbar','color',0,4,callback)

while True:
    # 获取trackbar 的值
    index = cv2.getTrackbarPos('trackbar','color')

    # 进行颜色空间转化
    cvt_img = cv2.cvtColor(img,color_spaces[index])

    cv2.imshow('color',cvt_img)

    key = cv2.waitKey( 10 )
    if key == ord('q'):
        break

cv2.destoryAllWindows()

error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window_w32.cpp:2581: error: (-27:Null pointer) NULL window: 'color' in function 'cvGetTrackbarPos'


### Mat 属性

In [ ]:
 # opencv 用 mat 这种数据结构来表示图片的
# C++ 中用 mat 来保存图片，python中把mat 转化成了 numpy 的 ndarray
cv2.imshow()

In [2]:
# img.channels

# ndarray 4种常见属性：
img.data

In [4]:
# 元素的总个数
img.size

3484575

In [6]:
img.dtype

dtype('uint8')

In [8]:
# 维度的形状
img.shape

(911, 1275, 3)

In [9]:
img.itemsize    # 并不属于Mat的属性

1

In [19]:
img.ndim    # 通道数

3

### 深浅拷贝

In [18]:
# 因为在 Python 中图片数据以及包装成 ndarray 了，所有对 mat 的深浅拷贝，其实就是对 ndarray 深浅拷贝
import cv2
import numpy as np

img = cv2.imread('./cat.jpg')

# 浅拷贝
img2 = img.view()

# 深拷贝
img3 = img.copy()

img[10:100,10:100] = [0,0,255]

cv2.imshow('img',np.hstack((img,img2,img3)))

cv2.waitKey(0)
cv2.destroyAllWindows()


In [10]:
# 图像的分割与融合
import cv2
import numpy as np

img = np.zeros((200,200,3),np.uint8)

# 分割通道
b,g,r = cv2.split(img)      # 分别用三个变量接收
print('b:',b)
# 修改一些颜色
b[10:100,10:100] = 255
g[10:100,10:100] = 255

# 合并通道
img2 = cv2.merge((b,g,r))

cv2.imshow('img',np.hstack((b,g)))
cv2.imshow('img2',np.hstack((img,img2)))

cv2.waitKey(0)
cv2.destoryAllWindows()

b: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


AttributeError: module 'cv2' has no attribute 'destoryAllWindows'

# 绘制图片
利用OpenCV 提供的绘制图形 API 可以在图像上绘制各种图形，比如直线、矩形、圆等图形

In [15]:
# 绘制直线和矩形
import cv2
import numpy as np

# 创建纯黑的背景图用来画图形
img = np.zeros((480,640,3),np.uint8)

# Line(img,pt1,pt2,color,thickness,lineType,shift) 画直线 pt1、pt2、color 为元组,lineType省略
cv2.line(img,(10,20),(400,20),(0,0,255),5,4)
cv2.line(img,(80,100),(380,480),(0,0,255),5,16)

# 和画线是完全完全一致的
cv2.rectangle(img,(80,100),(380,480),(0,255,0),5,8)


cv2.imshow('draw',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
# 绘制圆形
import cv2
import numpy as np

img = np.zeros((480,640,3),np.uint8)

# circle(img,center,radius,color[,thickness[,lineType[,shift]]]) 中括号内参数表示可选参数 ，画圆
cv2.circle(img,(320,240),100,(0,0,255),5,16)

cv2.imshow("draw",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
# 绘制椭圆
import cv2
import numpy as np

img = np.zeros((480,640,3),np.uint8)

# ellipse(img,中心点，长宽的一半，角度 ，从哪个角度开始，从哪个角度结束,…)
cv2.ellipse(img,(320,240),(100,50),45,0,180,[0,0,255],5,16)

cv2.imshow("draw",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
# 绘制多边形
import cv2
import numpy as np

img = np.zeros((480,640,3),np.uint8)

# pts 的点集 必须是 int 32位
pts = np. array([(250,100),(150,300),(50,280)],np.int32)
# cv2.polylines(img,[pts],True,(0,0,255),5)       # checkVector 检查维度，pts是3维的集合，应返回元组

cv2.fillPoly(img,[pts],(0,0,255))

cv2.imshow("draw",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

AttributeError: module 'cv2' has no attribute 'destroyAllWindow'

In [21]:
# 绘制文本信息
import cv2
import numpy as np

img = np.zeros((480,640,3),np.uint8)

# pts 的点集 必须是 int 32位
pts = np. array([(250,100),(150,300),(50,280)],np.int32)

# cv2.putText(img,'Hello OpenCV',(100,300),cv2.FONT_HERSHEY_SIMPLEX,4,(0,0,255) )
cv2.putText(img,'你好 OpenCV',(100,300),cv2.FONT_HERSHEY_SIMPLEX,4,(0,0,255) )

cv2.imshow("draw",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
# 使用OpenCV 绘制中文
# OpenCV 没有办法直接绘制中文，使用 Pillow 包
from PIL import ImageFont,ImageDraw,Image

# 纯白
# img = np.full((500,500,3),fill_value=255,dtype=np.uint8)
img = cv2.imread('./cat.jpg')

# 导入字体文件
font = ImageFont.truetype('./msyhbd.ttc',35)

# 创建一个 pillow 的图片
img_pil = Image.fromarray(img)

draw = ImageDraw.Draw(img_pil)
# 利用 draw 绘制中文
draw.text((200,10),"你好，OpenCV",font=font,fill=(0,255,0,0))

# 重新变回ndarray
img = np.array(img_pil)

cv2.imshow('img',img)

cv2.waitKey(0)
cv2.destroyAllWindows()