In [2]:
# 加法运算
import cv2
import numpy as np

# 读取图片
cat = cv2.imread('./cat.jpg')
dog = cv2.imread('./dog.jpg')

# 在做加法之前需要把图片的形状变得完全一致
"""
add的运算规则
两个图片对应位置的元素相加，如果超过255，全部变成255
两个图片对应位置的元素相减，如果相减完小于0，全部相当于0
相乘...大于255，归于255
相除...小于0，归于0
"""
# 1.通过 ndarray 的切片方式取出完全一样的形状
new_dog = dog[0:911,0:1080]
new_cat = cat[0:911,0:1080]
# print(new_cat[:3,:3])
# print("------------------")
# print(new_dog[:3,:3])
# print("==============")
# cv2.add 加法操作要求两个图片的长宽相同，通道数相同
# new_img = cv2.add(new_dog,new_cat)
# print(new_img[:3])

#图片还可以和单个数字进行运算
#每个元素和100 进行加法运算，超出255的元素会被截断，相当于 %255

# new_dog += 100
# print(new_dog[:3,:3])

# 乘法 multiply
new_img =  cv2.multiply(new_cat,new_dog)

# 除法 divide
new_img = cv2.divide(new_cat,new_dog)

# cv2.imshow('new_dog',new_dog)

cv2.imshow('new_img',new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
# 图像的融合（权重加法）
# 不是简单的加法，相当于拿图片做 线性运算 new_img = img*w1 + img*w2 + bias
import cv2
import numpy

cat = cv2.imread('./cat.jpg')
dog = cv2.imread('./dog.jpg')

new_dog = dog[0:911,0:1080]
new_cat = cat[0:911,0:1080]

new_img = cv2.addWeighted(new_cat,0.3,new_dog,0.7,0)

cv2.imshow('new_img',new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
# OpenCV 的逻辑运算 —— 与或非
# 异或符号 ^
1 ^ 1

# OpenCV 中的逻辑运算就是 对应位置元素进行与或非，异或
204 & 213 # 转换二进制进行运算

196

In [5]:
# OpenCV中的非，0 的非是 255

-256

In [16]:
import cv2
import numpy as np

cat = cv2.imread('./cat.jpg')
dog = cv2.imread('./dog.jpg')

# 图片的非操作 相当于 255-cat
# cat_not = cv2.bitwise_not(cat)
# cv2.imshow('not',np.hstack((cat,cat_not)))
# print(cat[:2,:2])
# print(cat_not[:2,:2])

# 切割图片
new_dog = dog[0:911,0:1080]
new_cat = cat[0:911,0:1080]
# 与操作
# cat_and = cv2.bitwise_and(new_cat,new_dog)
# cv2.imshow('and',np.hstack((cat,cat_and)))
# print(new_cat[:2,:2])
# print(new_dog[:2,:2])
# print(cat_and[:2,:2])

# 或操作
# cat_or = cv2.bitwise_or(new_cat,new_dog)
# cv2.imshow('or',np.hstack((cat,new_dog,cat_and)))
# print(new_cat[:2,:2])
# print(new_dog[:2,:2])
# print(cat_or[:2,:2])

# 异或操作
cat_xor = cv2.bitwise_xor(new_cat,new_dog)
cv2.imshow('xor',np.hstack((cat,new_dog,cat_xor)))
print(new_cat[:2,:2])
print(new_dog[:2,:2])
print(cat_xor[:2,:2])

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[ 40 154 254]
  [ 40 154 254]]

 [[ 42 156 255]
  [ 42 157 254]]]
[[[123 151 162]
  [117 145 156]]

 [[123 151 162]
  [116 144 155]]]
[[[ 83  13  92]
  [ 93  11  98]]

 [[ 81  11  93]
  [ 94  13 101]]]


# 图像的基本变换

In [26]:
import cv2

dog = cv2.imread('./dog.jpg')

print(dog.shape)
# print(cat.shape)

# 将猫缩放成狗的大小
# new_cat = cv2.resize(cat,(1080,911))
# new_dog = cv2.resize(dog,(1080,911))

# 还可以按照 x,y轴的比例 进行缩放
new_dog2 = cv2.resize(dog,dsize=None,fx=0.5,fy=0.5)
print(new_dog2.shape)
cv2.imshow('new_dog2',new_dog2)

# cv2.imshow('mix',np.hstack((new_cat,new_dog)))
cv2.imshow('dog',dog)

cv2.waitKey(0)
cv2.destroyAllWindows()

(1080, 1080, 3)
(540, 540, 3)


## 图像的翻转

In [6]:
# flip
import cv2
import numpy as np

dog = cv2.imread('./dog.jpg')
# flipCode=0,表示上下翻转
# flipCode>0,表示左右翻转
# flipCode<0,上下+左右翻转
new_dog = cv2.flip(dog,1)

cv2.imshow('new_dog',np.hstack((dog,new_dog)))
cv2.waitKey(0)
cv2.destroyAllWindows()

## 图像的旋转

In [11]:
import cv2

cat = cv2.imread('./cat.jpg')
# - ROTATE_90_CLOCKWISE  90度顺时针
# - ROTATE_180 180
# - ROTATE_90_COUNTERCLOCKWISE  90度逆时针
new_cat = cv2.rotate(cat,rotateCode=cv2.ROTATE_180)

cv2.imshow('new_cat',new_cat)

cv2.waitKey(0)
cv2.destroyAllWindows()

## 仿射变换之 平移

In [14]:
import cv2
import numpy as np

dog = cv2.imread('./dog.jpg')

h,w,ch = dog.shape
# 变换矩阵:最少是float32位
M = np.float32([[1,0,200],[0,1,100]])

# 平移操作
new_dog = cv2.warpAffine(dog,M,dsize=(w,h))

cv2.imshow('dog',dog)
cv2.imshow('new_dog',new_dog)

cv2.waitKey(0)
cv2.destroyAllWindows()

## 仿射变换之 获取变换矩阵

In [16]:
# 在进行旋转操作的时候，不方便手动计算变换矩阵
# OpenCV 提供了获取 变换矩阵的API
import cv2
import numpy as np

dog = cv2.imread('./dog.jpg')

h,w,ch = dog.shape

# 变换矩阵
# 规定按照逆时针旋转图片
M = cv2.getRotationMatrix2D((100,100),15,1)

new_dog = cv2.warpAffine(dog,M,dsize=(w,h))

cv2.imshow("dog",dog)
cv2.imshow('new_dog',new_dog)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
# 通过三个点确定变换矩阵
import cv2
import numpy as np

dog = cv2.imread('./dog.jpg')

h,w,ch = dog.shape

src = np.float32([[100,100],[200,100],[200,300]])
dst = np.float32([[100,150],[360,200],[280,120]])
# 需要原始图片的三个点坐标，和变换之后的三个对应的坐标
M = cv2.getAffineTransform(src,dst)
new_dog = cv2.warpAffine(dog,M,(w,h))

cv2.imshow('dog',dog)
cv2.imshow('new_dog',new_dog)

cv2.waitKey(0)
cv2.destroyAllWindows()

## 仿射变换之 透视变换

In [20]:
import cv2
import numpy as np

# 报错信息：215
# 断言失效：OpenCV可能无法找到图片路径；src指定坐标对应位置报错

img = cv2.imread('./toushi.jpg')

# 获取变换矩阵
# src是原图的 4 个坐标
src = np.float32([[80,200],[1000,25],[0,1500],[1200,1460]])
dst = np.float32([[0,0],[638,0],[0,851],[638,851]])
M = cv2.getPerspectiveTransform(src,dst)

# 透视变换
new_img = cv2.warpPerspective(img,M,(638,851))

cv2.imshow('img',img)
cv2.imshow('new_img',new_img)

cv2.waitKey(0)
cv2.destroyAllWindows()