# 阈值二值化

In [3]:
# 因为光线问题
import cv2
import numpy as np

img = cv2.imread('./toushi.jpg')

cv2.namedWindow('img',cv2.WINDOW_NORMAL)
cv2.resizeWindow('img',1920,1080)

# 二值化操作 时对灰度图像操作，把dog变成灰度图像
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

# 注意，threshold会返回两个值，一个阈值，与 二值化后处理后的图片
thresh,dst = cv2.threshold(gray,110,255,cv2.THRESH_BINARY)

print(thresh)

cv2.imshow('img',np.hstack((gray,dst)))
cv2.waitKey(0)
cv2.destoryAllWindows()

110.0


AttributeError: module 'cv2' has no attribute 'destoryAllWindows'

# 全局二值化

In [16]:
import cv2
import numpy as np

# 导入图片
img = cv2.imread('./dog.jpg')

# 二值化操作 时对灰度图像操作，把dog变成灰度图像
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

# threshold 会返回两个值，一个阈值，一个处理后的图片
thresh,dst = cv2.threshold(gray,120,255,cv2.THRESH_BINARY)

cv2.imshow('img',np.hstack((gray,dst)))
cv2.waitKey(0)
cv2.destoryAllWindows()

AttributeError: module 'cv2' has no attribute 'destoryAllWindows'

# 自适应阈值二值化

In [18]:
import cv2
import numpy as np

img = cv2.imread('./dog.jpg')

# 创建窗口调整显示大小

cv2.namedWindow('img',cv2.WINDOW_NORMAL)
cv2.resizeWindow('img',1920,1080)


gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

# 自适应阈值二值化 只会返回一个结果
dst = cv2.adaptiveThreshold(gray,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY_INV,3,0)

cv2.imshow('img',np.hstack((gray,dst)))
cv2.waitKey(0)
cv2.destoryAllWindows()

AttributeError: module 'cv2' has no attribute 'destoryAllWindows'

# 腐蚀操作

In [20]:
import cv2
import numpy as np

img = cv2.imread('./fushi.png')

# 定义核
kernel = np.ones((3,3),np.uint8)

dst = cv2.erode(img,kernel,iterations=2)

cv2.imshow('img',np.hstack((img,dst)))
cv2.waitKey(0)
cv2.destoryAllWindows()

AttributeError: module 'cv2' has no attribute 'destoryAllWindows'

# 获取形态学卷积核

In [28]:
import cv2
import numpy as np

img = cv2.imread('./fushi.png')

# - MORPH_RECT 卷积核中的 1
# - MORPH_ELLIPSE 椭圆
kernel = cv2.getStructuringElement(cv2.MORPH_CROSS,(5,5))
print(kernel)

# 腐蚀
dst = cv2.erode(img,kernel)

cv2.imshow('img',np.hstack((img,dst)))
cv2.waitKey(0)
cv2.destoryAllWindows()

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


AttributeError: module 'cv2' has no attribute 'destoryAllWindows'

# 膨胀操作

In [30]:
import cv2
import numpy as np

img = cv2.imread('./fushi.png')

kernel = cv2.getStructuringElement(cv2.MORPH_CROSS,(5,5))

# 先腐蚀再膨胀
dst1 = cv2.erode(img,kernel)
# 膨胀
dst2 = cv2.dilate(dst1,kernel,iterations=1)

cv2.imshow('img',np.hstack((img,dst1,dst2)))
cv2.waitKey(0)
cv2.destoryAllWindows()

AttributeError: module 'cv2' has no attribute 'destoryAllWindows'